#pragma once

#include "NativeGameplayTags.h"

namespace PX_GameplayTags
{
	// --- Input -----------------------------------------------------
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Move);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Look);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_ToggleInventory);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Locomotion_Jump);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Locomotion_Crouch);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Locomotion_Walk);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Locomotion_Sprint);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill_E);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Combat_Attack);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Combat_Attack_Bow);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Combat_Attack_Gun);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Combat_Reload);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Combat_SwitchAttackMode);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Combat_ImbueBurn);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Combat_ImbueSlow);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Combat_ImbueStun);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Combat_Aim);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Combat_Aim_ADS);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Combat_Aim_OTS);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip_BareHand);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip_Slot1);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip_Slot2);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip_Slot3);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip_Slot4);

	// --- Ability -----------------------------------------------------
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interaction_Interact);

	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Movement_Jump);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Movement_Crouch);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Movement_Walk);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Movement_Sprint);

	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Equip);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Unequip);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Switch);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Attack);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Attack_Gun);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_SwitchAttackMode);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Reload);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Aim);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Aim_ADS);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Aim_OTS);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_ImbueBurn);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_ImbueSlow);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_ImbueStun);

	// --- Event -----------------------------------------------------
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Weapon_Equip_Begin);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Weapon_Equip_End);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Weapon_Reload_End);

	// --- State -----------------------------------------------------
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Locomotion_Jogging);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Locomotion_Crouching);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Locomotion_Walking);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Locomotion_Sprinting);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Locomotion_Jumping);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Locomotion_Falling);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Locomotion_Swimming);

	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Action_Interacting);

	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Aiming);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Aiming_HipFire);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Aiming_ADS);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Aiming_OTS);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Attacking);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Attacking_Gun);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_SwitchAttackMode);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Reloading);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Equipping);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Unequipping);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_SwappingWeapon);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_HitReact);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Reviving);

	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Condition_Dead);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Condition_Down);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Condition_Disabled);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Condition_Invincible);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Condition_Stunned);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Condition_Silenced);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Condition_Bleeding);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Condition_Burning);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Condition_Slowed);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Condition_Poisoned);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Condition_Paralyzed);

	// --- Cooldown -----------------------------------------------------
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Movement_Jump);

	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Weapon_Attack);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Weapon_Reload);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Weapon_Switch);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Weapon_ImbueBurn);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Weapon_ImbueSlow);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Weapon_ImbueStun);

	// --- Item -----------------------------------------------------
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Equippable);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Equippable_Weapon);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Equippable_Armor);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Equippable_Accessory);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Consumable);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Ammo);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Material);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Quest);

	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Inventory_BareHand);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Inventory_Weapon);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Inventory_Armor);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Inventory_Accessory);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Inventory_General);

	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Stackable);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Droppable);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_NotDroppable);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Exchangeable);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_NotExchangeable);

	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_EquipSlot_BareHand);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_EquipSlot_Head);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_EquipSlot_Chest);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_EquipSlot_Legs);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_EquipSlot_Shoes);

	// --- Weapon -----------------------------------------------------
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Gun);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Gun_Pistol);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Gun_Rifle);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Gun_Shotgun);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Gun_SMG);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Gun_Sniper);

	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Bow);

	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Melee);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Melee_OneHandedSword);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Melee_TwoHandedSword);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Melee_Spear);

	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Throwing);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Throwing_Frag);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Throwing_Smoke);

	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_AttackMode_Single);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_AttackMode_Burst);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_AttackMode_Auto);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_AttackMode_Charge);
	PROJECT_X_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_AttackMode_Combo);
}
